// Generated by wm-domain. Run `cargo run -p wm-domain --bin export-contracts`.
// Do not edit by hand.

export type CreateGameRequest = { saveId: string, seed: string, };

export type PromotionOverview = { saveId: string, promotionId: string, name: string, initials: string, region: string, foundedOn: string, currentDate: string, cashPence: number, seed: string, engineVersion: string, schemaVersion: number, };

export type SaveSummary = { saveId: string, promotionName: string, currentDate: string, seed: string, };

export type IpcError = { code: string, message: string, };

export type Attributes = { strength: number, technical: number, psychology: number, stamina: number, charisma: number, safety: number, professionalism: number, improvisation: number, experience: number, };

export type Condition = { fatigue: number, confidence: number, morale: number, momentum: number, popularity: number, wear: number, injuryDays: number, development: number, matches: number, };

export type Move = { id: string, name: string, style: string, difficulty: number, risk: number, staminaCost: number, minStrength: number, proficiency: number, signature: boolean, };

export type Worker = { id: string, name: string, age: number, nationality: string, language: string, school: string, background: string, personality: string, ambition: string, style: string, weightKg: number, attributes: Attributes, condition: Condition, moves: Array<Move>, appearanceFee: number, };

export type RosterRow = { id: string, name: string, age: number, style: string, psychology: number, stamina: number, condition: Condition, };

export type RosterPage = { rows: Array<RosterRow>, total: number, };

export type RoadAgent = { id: number, name: string, psychology: number, communication: number, experience: number, safety: number, philosophy: string, knowledge: number, trust: number, };

export type BeatKind = "move" | "control" | "falseFinish" | "interference" | "weapon" | "refBump" | "callback" | "injurySell";

export type PlannedBeat = { atSecond: number, actorId: string, kind: BeatKind, moveId: string | null, durationSeconds: number, };

export type Finish = "pinfall" | "submission" | "countOut" | "disqualification" | "draw" | "noContest";

export type MatchPlan = { matchType: string, workerA: string, workerB: string, winnerId: string | null, finish: Finish, cleanFinish: boolean, durationSeconds: number, style: string, pace: number, risk: number, freedom: number, purpose: string, protectedWorkerId: string | null, agentId: number, beats: Array<PlannedBeat>, };

export type ParticipantSlot = { id: string, workerId: string, sideId: string, };

export type MatchSide = { id: string, };

export type ParticipationRule = "allActive" | "tag";

export type VictoryRule = "oneFall" | "elimination";

export type MatchRules = { participation: ParticipationRule, victory: VictoryRule, };

export type DecisionMethod = "pinfall" | "submission" | "countOut" | "disqualification";

export type BookedResult = { "outcome": "decision", winningSideId: string, method: DecisionMethod, decidingSlotId: string | null, defeatedSlotId: string | null, } | { "outcome": "draw", } | { "outcome": "noContest", };

export type MatchDefinition = { slots: Array<ParticipantSlot>, sides: Array<MatchSide>, rules: MatchRules, result: BookedResult, };

export type AnglePlan = { participants: Array<string>, purpose: string, durationSeconds: number, };

export type SegmentPlan = { "kind": "match", "plan": MatchPlan } | { "kind": "angle", "plan": AnglePlan };

export type Segment = { id: number, title: string, content: SegmentPlan, };

export type ShowCard = { id: number, name: string, date: string, status: string, revision: number, segments: Array<Segment>, capacitySeconds: number, };

export type SaveSegmentRequest = { saveId: string, showId: number, revision: number, segmentId: number | null, content: SegmentPlan, };

export type Cohort = { name: string, preference: string, energy: number, trust: number, fatigue: number, };

export type CrowdState = { energy: number, fatigue: number, expectation: number, trust: number, interferenceCount: number, peak: number, cohorts: Array<Cohort>, chant: string, };

export type Performance = { execution: number, psychology: number, engagement: number, safety: number, story: number, protection: number, };

export type SimEvent = { sequence: number, showSecond: number, segmentId: number, matchSecond: number, kind: string, text: string, actorId: string | null, moveId: string | null, importance: number, crowdEnergy: number, };

export type WorkerChange = { workerId: string, name: string, fatigue: number, confidence: number, morale: number, momentum: number, popularity: number, development: number, wear: number, injuryDays: number, note: string, };

export type SegmentReport = { segmentId: number, title: string, winnerId: string | null, result: string, durationSeconds: number, performance: Performance, reasons: Array<string>, changes: Array<WorkerChange>, chemistryChange: number, };

export type MediaPost = { id: number, author: string, text: string, date: string, };

export type ShowReport = { showId: number, name: string, date: string, segments: Array<SegmentReport>, crowd: CrowdState, attendance: number, revenuePence: number, costsPence: number, };

export type MatchView = { workerA: string, workerB: string, nameA: string, nameB: string, staminaA: number, staminaB: number, second: number, durationSeconds: number, phase: string, pace: number, risk: number, control: string, };

export type LiveView = { showId: number, tick: number, segmentIndex: number, complete: boolean, segmentTitle: string, currentMatch: MatchView | null, crowd: CrowdState, events: Array<SimEvent>, pendingInstructions: Array<string>, report: ShowReport | null, };

export type InstructionKind = "slowDown" | "raisePace" | "protect" | "goHome" | "extend" | "changeFinish" | "abandonSpot" | "takeRisks";

export type LiveInstruction = { kind: InstructionKind, workerId: string | null, finish: Finish | null, beatIndex: number | null, };

export type AdvanceRequest = { saveId: string, showId: number, expectedTick: number, seconds: number, };

export type AgentAdvice = { plan: MatchPlan, notes: Array<string>, };

export type CareerOffice = { promotion: PromotionOverview, show: ShowCard, agents: Array<RoadAgent>, rosterCount: number, media: Array<MediaPost>, recentShows: Array<ShowCard>, };

export type WorkerProfile = { worker: Worker, history: Array<SegmentReport>, };

export type NewsItem = { id: number, category: string, title: string, body: string, date: string, showId: number | null, workerId: string | null, read: boolean, };

export type NewsPage = { items: Array<NewsItem>, total: number, unread: number, };
