// Generated by wm-domain. Run `cargo run -p wm-domain --bin export-contracts`.
// Do not edit by hand.

export type CreateGameRequest = { saveId: string, seed: string, };

export type PromotionOverview = { saveId: string, promotionId: string, name: string, initials: string, region: string, foundedOn: string, currentDate: string, cashPence: number, seed: string, engineVersion: string, schemaVersion: number, };

export type SaveSummary = { saveId: string, promotionName: string, currentDate: string, seed: string, };

export type IpcError = { code: string, message: string, };

export type AlignmentIntent = "face" | "heel" | "tweener" | "unaligned";

export type AudienceResponse = "cheered" | "booed" | "mixed" | "indifferent";

export type PerceivedRole = "face" | "heel" | "mixed" | "unclear";

export type ReactionIntensity = "mild" | "moderate" | "strong";

export type CharacterAcceptance = "embraced" | "accepted" | "uncertain" | "rejected";

export type IntentMatch = "matched" | "mismatched" | "ambiguous";

export type IdentityKnowledge = "private" | "rumoured" | "public";

export type CharacterStatus = "planned" | "active" | "retired";

export type ChangeStatus = "proposed" | "negotiating" | "accepted" | "refused" | "ready" | "launched" | "cancelled";

export type GimmickBrief = { name: string, description: string, coreFantasy: string, tags: Array<string>, tone: string, promoVoice: string, presentationIntensity: string, entranceAndMatchBehavior: string, attireAndMask: string, catchphrasesAndGestures: string, traitsToEmphasize: Array<string>, };

export type CharacterIdentity = { id: string, revision: number, ringName: string, alignmentIntent: AlignmentIntent, status: CharacterStatus, masked: boolean, concealed: boolean, gimmick: GimmickBrief, companyId: string, brand: string | null, startedOn: string, endedOn: string | null, aliases: Array<string>, identityKnowledge: IdentityKnowledge, };

export type AudienceResponseEvidence = { date: string, perceivedRole: PerceivedRole, response: AudienceResponse, intensity: ReactionIntensity, acceptance: CharacterAcceptance, intentMatch: IntentMatch, context: string, };

export type CharacterChange = { id: bigint, requestId: string, proposedRingName: string, proposedAlignment: AlignmentIntent, proposedMasked: boolean, proposedConcealed: boolean, proposedGimmick: GimmickBrief, status: ChangeStatus, revision: number, proposedOn: string, intendedLaunchOn: string | null, launchedOn: string | null, workerResponse: string, readiness: string, risk: string, advice: Array<string>, };

export type CharacterProfile = { legalName: string | null, active: CharacterIdentity, history: Array<CharacterIdentity>, audienceResponses: Array<AudienceResponseEvidence>, pendingChange: CharacterChange | null, };

export type ProposeCharacterChangeRequest = { saveId: string, workerId: string, requestId: string, expectedRevision: number, ringName: string, alignmentIntent: AlignmentIntent, masked: boolean, concealed: boolean, intendedLaunchOn: string | null, gimmick: GimmickBrief, };

export type CharacterActionRequest = { saveId: string, workerId: string, requestId: string, changeId: bigint | null, expectedRevision: number, };

export type SortDirection = "ascending" | "descending";

export type WorkerSortKey = "relevance" | "name" | "age" | "overall" | "movement" | "physicality" | "ringcraft" | "psychology" | "fundamentals" | "entertainment" | "fatigue" | "morale" | "momentum";

export type WorkerSort = { key: WorkerSortKey, direction: SortDirection, };

export type NumberRange = { minimum: number | null, maximum: number | null, };

export type WorkerAvailability = "any" | "cleared" | "injured";

export type BlacklistMode = "include" | "exclude" | "only";

export type WorkerSearchFilters = { age: NumberRange, overall: NumberRange, movement: NumberRange, physicality: NumberRange, ringcraft: NumberRange, psychology: NumberRange, fundamentals: NumberRange, entertainment: NumberRange, nationalities: Array<string>, excludedNationalities: Array<string>, languages: Array<string>, excludedLanguages: Array<string>, schools: Array<string>, excludedSchools: Array<string>, archetypes: Array<string>, excludedArchetypes: Array<string>, primaryDisciplines: Array<string>, excludedPrimaryDisciplines: Array<string>, availability: WorkerAvailability, shortlistId: number | null, blacklist: BlacklistMode, };

export type WorkerSearchRequest = { text: string, filters: WorkerSearchFilters, sort: Array<WorkerSort>, offset: number, limit: number, };

export type WorkerSearchHit = { worker: RosterRow, matchReason: string | null, shortlistIds: Array<number>, blacklisted: boolean, };

export type WorkerSearchPage = { rows: Array<WorkerSearchHit>, total: number, };

export type WorkerFilterOptions = { nationalities: Array<string>, languages: Array<string>, schools: Array<string>, archetypes: Array<string>, primaryDisciplines: Array<string>, };

export type SavedWorkerView = { id: number, name: string, request: WorkerSearchRequest, columns: Array<string>, };

export type WorkerShortlist = { id: number, name: string, memberCount: number, };

export type WorkerDiscoveryLists = { savedViews: Array<SavedWorkerView>, shortlists: Array<WorkerShortlist>, blacklistCount: number, };

export type Rating100 = number;

export type IdentityVisibility = { "kind": "public" } | { "kind": "company", "companyId": string } | { "kind": "hidden" };

export type Assessment = { value: Rating100 | null, visibility: IdentityVisibility, source: string, };

export type PersonalityField = "ambition" | "sociability" | "empathy" | "loyalty" | "ego" | "integrity" | "temperament" | "outspokenness";

export type QualityField = "communication" | "leadership" | "creativity" | "personalAdaptability" | "organisation" | "professionalism" | "workEthic" | "stressManagement" | "teaching";

export type Motivation = "achievement" | "fame" | "money" | "stability" | "belonging" | "wrestlingCraft" | "entertainment" | "creativeInfluence" | "exploration" | "legacy";

export type Motivations = { primary: Motivation, secondary: Array<Motivation>, };

export type Hobby = "gaming" | "music" | "acting" | "fashion" | "fitness" | "combatSports" | "sports" | "cars" | "travel" | "cooking" | "outdoors" | "reading" | "art" | "collecting" | "charity" | "nightlife";

export type Involvement = "casual" | "regular" | "passionate";

export type LanguageLevel = "basic" | "conversational" | "fluent";

export type BiographyMode = "authored" | "organic" | "hybrid";

export type SpokenLanguage = { name: string, proficiency: LanguageLevel | null, native: boolean, };

export type Interest = { hobby: Hobby, involvement: Involvement, };

export type Biography = { mode: BiographyMode, authoredText: string, birthplace: string | null, debutYear: number | null, trainers: Array<string>, previousOccupations: Array<string>, };

export type PersonIdentity = { personality: { [key in PersonalityField]?: Assessment }, qualities: { [key in QualityField]?: Assessment }, motivations: Motivations | null, languages: Array<SpokenLanguage>, hobbies: Array<Interest>, biography: Biography, };

export type PersonalityDescriptor = { field: string, label: string, source: string, };

export type PersonalityDescription = { ruleVersion: number, text: string, partial: boolean, reasons: Array<PersonalityDescriptor>, };

export type ExceptionalTrait = "mediaLiability" | "wellnessComplianceRisk" | "sponsorFriendly" | "companyIcon" | "crossoverCelebrity";

export type TraitStatus = "inactive" | "active" | "elevated" | "historical";

export type TraitState = { traitId: ExceptionalTrait, companyId: string | null, visibility: IdentityVisibility, status: TraitStatus, evidenceIds: Array<string>, };

export type TraitTransition = { date: string, ruleVersion: number, from: TraitStatus, state: TraitState, reason: string, };

export type TraitOverview = { states: Array<TraitState>, history: Array<TraitTransition>, hasEvidence: boolean, };

export type MovementAttributes = { acceleration: Rating100, ringSpeed: Rating100, agility: Rating100, acrobatics: Rating100, jumping: Rating100, flexibility: Rating100, balance: Rating100, };

export type PhysicalityAttributes = { strength: Rating100, stamina: Rating100, toughness: Rating100, recovery: Rating100, injuryResistance: Rating100, };

export type RingcraftAttributes = { technicalGrappling: Rating100, chainWrestling: Rating100, striking: Rating100, brawling: Rating100, submissions: Rating100, aerialWrestling: Rating100, powerOffense: Rating100, hardcoreWeapons: Rating100, countering: Rating100, };

export type PsychologyAttributes = { matchStorytelling: Rating100, pacing: Rating100, selling: Rating100, crowdReading: Rating100, matchCalling: Rating100, adaptability: Rating100, };

export type FundamentalsAttributes = { timing: Rating100, consistency: Rating100, safety: Rating100, bumping: Rating100, positioning: Rating100, cooperation: Rating100, };

export type EntertainmentAttributes = { presence: Rating100, microphone: Rating100, characterPerformance: Rating100, crowdConnection: Rating100, };

export type WrestlerAttributes = { movement: MovementAttributes, physicality: PhysicalityAttributes, ringcraft: RingcraftAttributes, psychology: PsychologyAttributes, fundamentals: FundamentalsAttributes, entertainment: EntertainmentAttributes, };

export type Discipline = "technicalGrappling" | "submissionWrestling" | "luchaLibre" | "aerialWrestling" | "striking" | "powerWrestling" | "brawling" | "hardcoreWrestling" | "shootFighting";

export type Tempo = "methodical" | "balanced" | "fastPaced";

export type Structure = "traditional" | "escalating" | "spotDriven";

export type Presentation = "sportRealistic" | "dramatic" | "spectacle" | "comedy";

export type Contact = "light" | "standard" | "stiff";

export type RiskApproach = "conservative" | "balanced" | "daredevil";

export type Specialisation = "chainWrestling" | "catchWrestling" | "matControl" | "counterWrestling" | "jointLocks" | "chokes" | "stretchHolds" | "limbTargeting" | "ropework" | "luchaGrappling" | "luchaSequences" | "multiPersonFlow" | "diving" | "springboards" | "slingshots" | "aerialCounters" | "punches" | "kicks" | "kneesElbows" | "chopsForearms" | "lifts" | "presses" | "impactSlams" | "throws" | "clinchFighting" | "dirtyFighting" | "arenaBrawling" | "weapons" | "tablesLadders" | "environmentalOffense" | "deathmatch" | "takedowns" | "groundControl" | "groundAndPound" | "martialArtsIntegration";

export type WrestlingApproach = { tempo: Tempo, structure: Structure, presentation: Presentation, contact: Contact, risk: RiskApproach, };

export type DisciplineEvidence = { discipline: Discipline, movesetReadiness: Rating100, mastery: Rating100, provenPerformance: Rating100, };

export type WrestlingStyleProfile = { evidence: Array<DisciplineEvidence>, approach: WrestlingApproach, specialisations: Array<Specialisation>, ringExperience: Rating100, performanceModifier: number, currentPrimary: Discipline, pendingPrimary: Discipline | null, pendingDays: number, pendingMatches: number, };

export type GroupScores = { movement: Rating100, physicality: Rating100, ringcraft: Rating100, psychology: Rating100, fundamentals: Rating100, entertainment: Rating100, };

export type DisciplineFit = { discipline: Discipline, score: Rating100, };

export type WrestlingSummary = { groups: GroupScores, disciplineFits: Array<DisciplineFit>, primary: Discipline, secondaries: Array<Discipline>, archetype: string, overall: Rating100, developing: boolean, };

export type RelationshipMemoryKind = "sharedBackground" | "positiveExperience" | "disagreement" | "betrayal" | "support" | "reconciliation" | "managementConversation";

export type InteractionKind = "introduceYourself" | "checkIn" | "praiseRecentWork" | "offerEncouragement" | "askForCreativeInput" | "discussColleague" | "clearTheAir";

export type InteractionTone = "warm" | "open" | "guarded" | "defensive";

export type RelationshipSignals = { affinity: string, respect: string, trust: string, tension: string, };

export type RelationshipMemoryView = { id: string, occurredOn: string, kind: RelationshipMemoryKind, summary: string, active: boolean, };

export type PersonalRelationshipView = { otherId: string, otherName: string, summary: string, signals: RelationshipSignals, memories: Array<RelationshipMemoryView>, };

export type ManagementRelationshipView = { summary: string, signals: RelationshipSignals, revision: number, };

export type RelationshipDelta = { affinity: number, respect: number, trust: number, tension: number, };

export type InteractionTarget = { workerId: string, name: string, relationship: string, };

export type InteractionTargetPage = { rows: Array<InteractionTarget>, total: number, };

export type InteractionOption = { kind: InteractionKind, label: string, description: string, enabled: boolean, unavailableReason: string | null, attentionCost: number, cooldownUntil: string | null, requiresTarget: boolean, };

export type InteractionOutcome = { requestId: string, workerId: string, kind: InteractionKind, label: string, occurredOn: string, tone: InteractionTone, response: string, factors: Array<string>, relationshipDelta: RelationshipDelta, moraleDelta: number, confidenceDelta: number, effects: Array<string>, contextWorkerId: string | null, };

export type RelationshipProfile = { ruleVersion: number, management: ManagementRelationshipView, personal: Array<PersonalRelationshipView>, interactionOptions: Array<InteractionOption>, interactionHistory: Array<InteractionOutcome>, attentionRemaining: number, attentionLimit: number, };

export type InteractionRequest = { saveId: string, requestId: string, workerId: string, kind: InteractionKind, contextWorkerId: string | null, expectedRevision: number, };

export type Condition = { fatigue: number, confidence: number, morale: number, momentum: number, popularity: number, wear: number, injuryDays: number, development: number, matches: number, };

export type Move = { id: string, name: string, style: string, difficulty: number, risk: number, staminaCost: number, minStrength: number, proficiency: number, signature: boolean, };

export type Worker = { id: string, name: string, age: number, nationality: string, language: string, school: string, background: string, personality: string, ambition: string, identity: PersonIdentity, style: string, weightKg: number, attributes: WrestlerAttributes, wrestlingStyle: WrestlingStyleProfile, condition: Condition, moves: Array<Move>, appearanceFee: number, };

export type RosterRow = { id: string, name: string, age: number, style: string, archetype: string, overall: number, personalityDescription: string, groups: GroupScores, condition: Condition, };

export type RosterPage = { rows: Array<RosterRow>, total: number, };

export type RoadAgent = { id: number, name: string, psychology: number, communication: number, experience: number, safety: number, philosophy: string, knowledge: number, trust: number, };

export type BeatKind = "move" | "control" | "falseFinish" | "interference" | "weapon" | "refBump" | "callback" | "injurySell";

export type PlannedBeat = { atSecond: number, actorId: string, kind: BeatKind, moveId: string | null, durationSeconds: number, };

export type Finish = "pinfall" | "submission" | "countOut" | "disqualification" | "draw" | "noContest";

export type MatchPlan = { matchType: string, workerA: string, workerB: string, winnerId: string | null, finish: Finish, cleanFinish: boolean, durationSeconds: number, style: string, pace: number, risk: number, freedom: number, purpose: string, protectedWorkerId: string | null, agentId: number, beats: Array<PlannedBeat>, };

export type ParticipantSlot = { id: string, workerId: string, sideId: string, };

export type MatchSide = { id: string, };

export type ParticipationRule = "allActive" | "tag";

export type VictoryRule = "oneFall" | "elimination";

export type MatchRules = { participation: ParticipationRule, victory: VictoryRule, };

export type DecisionMethod = "pinfall" | "submission" | "countOut" | "disqualification";

export type BookedResult = { "outcome": "decision", winningSideId: string, method: DecisionMethod, decidingSlotId: string | null, defeatedSlotId: string | null, } | { "outcome": "draw", } | { "outcome": "noContest", };

export type MatchDefinition = { slots: Array<ParticipantSlot>, sides: Array<MatchSide>, rules: MatchRules, result: BookedResult, };

export type AnglePlan = { participants: Array<string>, purpose: string, durationSeconds: number, };

export type SegmentPlan = { "kind": "match", "plan": MatchPlan } | { "kind": "angle", "plan": AnglePlan };

export type Segment = { id: number, title: string, content: SegmentPlan, };

export type ShowCard = { id: number, name: string, date: string, status: string, revision: number, segments: Array<Segment>, capacitySeconds: number, };

export type SaveSegmentRequest = { saveId: string, showId: number, revision: number, segmentId: number | null, content: SegmentPlan, };

export type Cohort = { name: string, preference: string, energy: number, trust: number, fatigue: number, };

export type CrowdState = { energy: number, fatigue: number, expectation: number, trust: number, interferenceCount: number, peak: number, cohorts: Array<Cohort>, chant: string, };

export type Performance = { execution: number, psychology: number, engagement: number, safety: number, story: number, protection: number, };

export type SimEvent = { sequence: number, showSecond: number, segmentId: number, matchSecond: number, kind: string, text: string, actorId: string | null, moveId: string | null, importance: number, crowdEnergy: number, };

export type WorkerChange = { workerId: string, name: string, fatigue: number, confidence: number, morale: number, momentum: number, popularity: number, development: number, wear: number, injuryDays: number, note: string, };

export type SegmentReport = { segmentId: number, title: string, winnerId: string | null, result: string, durationSeconds: number, performance: Performance, reasons: Array<string>, changes: Array<WorkerChange>, chemistryChange: number, };

export type MediaPost = { id: number, author: string, text: string, date: string, };

export type ShowReport = { showId: number, name: string, date: string, segments: Array<SegmentReport>, crowd: CrowdState, attendance: number, revenuePence: number, costsPence: number, };

export type MatchView = { workerA: string, workerB: string, nameA: string, nameB: string, staminaA: number, staminaB: number, second: number, durationSeconds: number, phase: string, pace: number, risk: number, control: string, };

export type LiveView = { showId: number, tick: number, segmentIndex: number, complete: boolean, segmentTitle: string, currentMatch: MatchView | null, crowd: CrowdState, events: Array<SimEvent>, pendingInstructions: Array<string>, report: ShowReport | null, };

export type InstructionKind = "slowDown" | "raisePace" | "protect" | "goHome" | "extend" | "changeFinish" | "abandonSpot" | "takeRisks";

export type LiveInstruction = { kind: InstructionKind, workerId: string | null, finish: Finish | null, beatIndex: number | null, };

export type AdvanceRequest = { saveId: string, showId: number, expectedTick: number, seconds: number, };

export type AgentAdvice = { plan: MatchPlan, notes: Array<string>, };

export type CareerOffice = { promotion: PromotionOverview, show: ShowCard, agents: Array<RoadAgent>, rosterCount: number, media: Array<MediaPost>, recentShows: Array<ShowCard>, };

export type WorkerProfile = { worker: Worker, wrestling: WrestlingSummary, history: Array<SegmentReport>, personalityDescription: PersonalityDescription, biography: string, exceptionalTraits: TraitOverview, relationships: RelationshipProfile, character: CharacterProfile, };

export type NewsItem = { id: number, category: string, title: string, body: string, date: string, showId: number | null, workerId: string | null, read: boolean, };

export type NewsPage = { items: Array<NewsItem>, total: number, unread: number, };
